### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Tristramg** [OpenTransport/Stations#2]
Under what licence should be the database be published?

There will inevitably be some incompatibilities.
I suggest the ODbL, to be compatible with OpenStreetMap from which we can make a bulk extraction from it.

Less restrictive licences might be included directly.
More restrictive licences won’t ever match.

**Comment by pietercolpaert** [comment]
I always thought of CC0 for this. But I'm fine with ODBL

**Comment by Tristramg** [comment]
The problem is that with CC0, we won’t be able to take data that is ODbL. In France at least it is a very common format for opendata.
And of course OSM…

**Comment by pietercolpaert** [comment]
How about always trying to have as permissive and open as possible? If some data we import needs attribution or has other clauses to it, so be it, we add that to that part of the dataset then? Or is that too complicated?

**Comment by Tristramg** [comment]
I have to spend some time on licences to know what exactly is possible. Let’s leave the issue open until someone confirms how ODbL would behave in such a database.

**Comment by rufuspollock** [comment]
@Tristramg what do you need clarifying re how ODbL would behave? It seems to me that you could dual license individual contributions and have overall DB under ODbL to ensure compatibility with any OSM data you import.

**Comment by Tristramg** [comment]
@pietercolpaert suggested to put the database under CC0, while I suggested ODbL.

Openstreetmap considers that « significant » is about 100 features. We will easily reach that limit (a very rough guess is that there are about 100 000 stop areas in Europe). This means that we will have to redistribute this database as ODbL.

**Comment by pietercolpaert** [comment]
@Tristramg let's dual license it?

**Comment by Tristramg** [comment]
Let’s discuss it at OKCon. I have no strong opinion on the licences. However I’m worried about the implication in using licenced data.
We are not creating new data, we are just aggregating existing data.

**Comment by pietercolpaert** [comment]
Maybe we can do license composition as explained in (this paper)[https://www.google.be/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CC0QFjAA&url=http%3A%2F%2Fiswc2012.semanticweb.org%2Fsites%2Fdefault%2Ffiles%2Fpaper_23.pdf&ei=lFNlUozUIeSp0QWkvYCYCg&usg=AFQjCNG3AQqfNkigxRCqJQsIFPArqNoohQ&sig2=eW5DCP_Njrbg69s3esdL3g&bvm=bv.54934254,d.d2k] by S. Villata et al.

For this purpose, we will now solve the issue as follows:
- If we add a certain dataset, we keep the original license.
- If we add a dataset we made ourselves, we are licensing it under CC0
- If we are aggregating the datasets, there will be a complex license which applies different rights on different parts of the dataset ("reuser's problem")
