### ISSUE TITLE
Peer-review per pull requests vs. auto-regulation

### ISSUE THREAD

**Issue by Tristramg** [OpenTransport/Stations#4]
We suggested that new contributions to the database should be done through pull requests.

I like the idea a lot. However this would almost be a “regression” in terms of open contributions compared to Wikipedia or OpenStreetMap where contributions are not “Validated” by somebody else.

Maybe the difference here is that we work on the whole database. A later interface where everybody can edit could be open. In the meantime, this avoids us to handle identification, history, etc.

What is your opinion to it?

**Comment by rufuspollock** [comment]
My 2c: I think pull requests are fine and those with "committer" status can just commit directly :-)

**Comment by Tristramg** [comment]
I agree.
If we find out it is too cumbersome, we can change it later.
I keep the question still open for a few days/weeks to see if other have an
opinion, otherwise we can close it for now.

**Comment by pietercolpaert** [comment]
+1 for Rufus :)
